### ISSUE TITLE
Add columns to export csv

### ISSUE THREAD

**Issue by joeb37** [CS599-MEDLINE/pubminer-web-app#61]
Add these columns to the export csv
- PMC id
- Sentences available? y/n
- Table 1 available? y/n

**Comment by freshottr** [comment]
Do we currently include the query that generated the results? I think that was part of the original requirements

**Comment by joeb37** [comment]
Fixed by #72.

There is still an open question about whether to include the search query, as originally requested by the customer.  The standard for CSV files says that all rows must have the same number of columns.  Not sure if we can add a line with just the search query and continue to treat the output as a CSV.

**Comment by joeb37** [comment]
The search term is added as a value for each result row.  This preserves csv structure of the file and permits a user to (manually) collect several exports into a single document or spreadsheet.
