### ISSUE TITLE
UI should clear previous error message when doing new search

### ISSUE THREAD

**Issue by freshottr** [CS599-MEDLINE/pubminer-web-app#82]
The UI will show an error for any search that wasn't able to be serviced. When the user does a new search, this error message remains on the UI while the progress bar is loading. The error messages should be removed once the user submits a new query. 

<img width="964" alt="error message while loading" src="https://user-images.githubusercontent.com/5361710/39096228-3c7c0eb6-461b-11e8-8cfc-cf111a48c5dc.png">

**Comment by joeb37** [comment]
Fixed with #84
